---

- name: CONSUL_TEMPLATE | Install
  include_tasks: install.yml
  tags:
    - consul_template_install

- name: CONSUL_TEMPLATE | Configure
  include_tasks: config.yml
  tags:
    - consul_template_configure

- name: CONSUL_TEMPLATE | Service
  include_tasks: service.yml
  tags:
    - consul_template_service
